version: '3.9'

services:
    postgres:
        image: postgres:14-alpine
        ports:
            - 5432:5432
        volumes:
            - ~/apps/postgres:/var/lib/postgresql/datas
        environment:
            - POSTGRES_PASSWORD=test
            - POSTGRES_USER=rizqi
            - POSTGRES_DB=chat
